### ISSUE TITLE
Suggestion - Specific Time

### ISSUE THREAD

**Issue by ibigfire** [enra4/discord-schedule-messages#2]
Hiya,

This is fantastic.  It would be icing on the cake if we could input a specific time for it to go off instead of simply a certain number of seconds from now.  I'm far from any sort of expert, but this package may help: https://www.npmjs.com/package/moment although I'm not sure.  Either way though, thank you very much for this!

**Comment by enra4** [comment]
happily surprised someone somehow found this app useful, anyway i did your suggestion here https://github.com/enra4/discord-schedule-messages/commit/b92be3d42dbc4ba2291a8d7d73f03bc45b058116

use `send-date` instead of `send` though, see the [readme](https://github.com/enra4/discord-schedule-messages/blob/master/README.md)
